#!/usr/bin/env bash
# Script that displays numbers from 1 to 100
for ((n = 1; n <= 100; ++n))
do
    if (( n % 3 && n % 5 ))
    then
        echo "$n"
    else
        (( n % 3 )) || echo -n 'Fizz'
        (( n % 5 )) || echo -n 'Buzz'
        echo
    fi
done
