#!/usr/bin/env bash
#  Script that loops from 1 to 10
i=0
while (( i++ < 20 ))
do
    echo $i
    if (( i == 4 ))
    then
        echo "bad luck from China"
    elif (( i == 9 ))
    then
        echo "bad luck from Japan"
    elif (( i == 17 ))
    then
        echo "bad luck from Italy"
    fi
done
