#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

hr=0
while (( hr < 13 ))
do
    echo "Hour: $((hr++))"
    min=1
    while (( min < 60 ))
    do
        echo "$((min++))"
    done
done
